name: Deploy MLB Storyteller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions configuration
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
        create_credentials_file: true
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io --quiet

    - name: Build and Push Application Container
      run: |
        docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/mlb-storyteller:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/mlb-storyteller:${{ github.sha }}

    - name: Setup Cloud Infrastructure
      if: github.ref == 'refs/heads/main'
      run: |
        # Enable required APIs
        gcloud services enable \
          redis.googleapis.com \
          datastore.googleapis.com \
          vpcaccess.googleapis.com \
          servicenetworking.googleapis.com \
          run.googleapis.com

        # Create VPC network if it doesn't exist
        if ! gcloud compute networks describe mlb-network 2>/dev/null; then
          gcloud compute networks create mlb-network --subnet-mode=auto
        fi

        # Create Cloud Memorystore (Redis) instance if it doesn't exist
        if ! gcloud redis instances describe mlb-redis --region=${{ secrets.GCP_REGION }} 2>/dev/null; then
          gcloud redis instances create mlb-redis \
            --size=1 \
            --region=${{ secrets.GCP_REGION }} \
            --network=mlb-network \
            --redis-version=redis_6_x
        fi

        # Get Redis instance IP
        REDIS_IP=$(gcloud redis instances describe mlb-redis --region=${{ secrets.GCP_REGION }} --format='get(host)')
        echo "REDIS_IP=$REDIS_IP" >> $GITHUB_ENV

        # Create Serverless VPC connector if it doesn't exist
        if ! gcloud compute networks vpc-access connectors describe mlb-connector --region=${{ secrets.GCP_REGION }} 2>/dev/null; then
          gcloud compute networks vpc-access connectors create mlb-connector \
            --network=mlb-network \
            --region=${{ secrets.GCP_REGION }} \
            --range=10.8.0.0/28
        fi

        # Set Datastore environment variables
        echo "DATASTORE_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}" >> $GITHUB_ENV
        echo "DATASTORE_NAMESPACE=mlb_storyteller" >> $GITHUB_ENV

    - name: Create env file
      run: |
        echo "DATASTORE_PROJECT=${DATASTORE_PROJECT}" >> .env
        echo "DATASTORE_NAMESPACE=${DATASTORE_NAMESPACE}" >> .env
        echo "REDIS_URL=redis://${REDIS_IP}:6379" >> .env
        echo "CACHE_ENABLED=True" >> .env
        echo "CACHE_TTL=3600" >> .env
        echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}" >> .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

    - name: Run tests
      run: |
        # Install Docker Compose v2
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
        # Run tests using Docker Compose v2
        docker compose -f docker-compose.test.yml up --exit-code-from tests

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Copy index.html to frontend directory
      run: |
        cp index.html frontend/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'

    - name: Deploy Application to Cloud Run
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud run deploy mlb-storyteller \
          --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/mlb-storyteller:${{ github.sha }} \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --vpc-connector mlb-connector \
          --allow-unauthenticated \
          --timeout 300 \
          --cpu 1 \
          --memory 512Mi \
          --set-env-vars "DATASTORE_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}" \
          --set-env-vars "DATASTORE_NAMESPACE=mlb_storyteller" \
          --set-env-vars "REDIS_URL=redis://${REDIS_IP}:6379" \
          --set-env-vars "GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}" \
          --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" 